### ISSUE TITLE
3 - Epic: Generate BLS Keys when membership change (DKG):

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/routing#1771]
(No dependencies)
 (to big to really estimate: need split initial estimate 2-4 Weeks)(Estimate after break down: 11-20 days)

 - Still use bls_emu (real key only generated, but not used for trust).
 - Ensure new nodes are ready to get Parsec data before generating BLS (NodeApproval RPC) -> No longer proving state/now participate in gossip.
 - BLS Key should ideally be generated before new SectionInfo is voted into parsec. (Probably what we want is to be able to put new SectionInfo (+sig if needed) + BLS Public Key + sign by old BLS Key, then that event accumulating would give use all we need to swich to new membership).
 - (Maybe should be in 4.) Each node should store the last real BLS public and secret key (if available) in SharedState (only public part is serialized), (probably only temporary until we stop using bls_emu).
 - Handle split appropriately.
     - There are 2 DKGS to run + 2 SectionInfo to consensus upfront before split.
     - Will eventually need to sign both new keys with previous key.
     - Each 1/2 of the section participate in their DKG. 
     - Need to keep the right Public Key.
 - Mock parsec DKG.

Possible option do DKG + new section info before split and then 2 DKG with same members splitted and 2 new section. (Maybe simpler in some way more complex in other).

Tasks:
 - [x] Mock parsec DKG. (2-4 days) https://github.com/maidsafe/routing/issues/1772
   Simplest DKG with test for the mock (not used in prod).
   Output real BLS keys and secret share (not real DKG: compute all shares and keys and output it.)
   Very easy with trusted dealer. 
   
 - [x] New node needs to participate in DKG. (2-4 days should cover risk, but possible unkown) https://github.com/maidsafe/routing/issues/1773
   (should already be part of `peer_manager` connected, so should receive gossip once DkgStart consensus).
   Will it accept it?
   Adult state is handling parsec gossip.
   => But need to be in adult state (Maybe will just work).
   => Maybe can call `handle_candidate_approval` in `handle_online_event`
   => Maybe in this task, in `handle_online_event` also vote to start DKG as well as Add, but ignore output.
   => Test
   => Risk (small change in order of things, but not really impact elder, and ProvingNode becoming an adult receive a message in same order so should not have impact either).

 - [x] start DKG when membership change (1-4 days) https://github.com/maidsafe/routing/issues/1774
   Could be Online -> DKG (DKG complete) -> Add (need to have stored info) -> SectionInfo
   Maybe in case of split: Online -> DKG (DKG complete) -> (No need for Add) SectionInfo
   => vote for DkgStart in `handle_online_event`.
   => Only vote for Add or remove when DkgResult comes back out of parsec as oppose to in `handle_online_event`.
   => Does not cater for split.

**MOVED to be part of first task of Epic 4 where it fits better since we use that result we store**

 - Use DKG result Block. (1-2 day) https://github.com/maidsafe/routing/issues/1777
   Store the right block (i.e use the right key/section before moving into next section after split.
   If SectionInfo and PublicKey (+ sign eventually) in same block, do the same selection we do now.

**NO LONGER RELEVANT as we now reset Parsec for each member change and don't AddElder:**

 -  (can be before or after adding DKG) Move splitting decision to `handle_online_event` (1-3 days) https://github.com/maidsafe/routing/issues/1775
   => Only needed for option B.
   => Need the new membership for DKGs.
   => so that we can use it in DKG (Can still only start 1 DKG for 1 half of the split)
   => Probably need to store it so we can use it in SectionInfo (but not necessary)
   => Quite tricky?

 - DKG for split case: https://github.com/maidsafe/routing/issues/1776
   Option A (3DKG + extra SectionInfo?): (1 week)
    => AddElder event (=> add_member returning 2 SectionInfo)
    ==> Change it to only return a single SectionInfo?
    ==> Or modify handle_add_elder check if single or 2. If more start DkgStart.
    ==> Previous extra keys stored and used in the middle (need to fix correspondance on SectionInfo and SectionInfo)(1/2 day), or discard the key from split (can you really not just add it) (1/2 day).
    ==> Change in code that handle DkgResult get 2 but only one relevant to our section, but still need to sign both (1 day).
    ==> (no split) Online -> DKG -> Add (know what to add/remove) -> Vote SectionInfo and signed PublicKey -wait-> Finished
    ==> (split) Online -> DKG -> Add (know what to add/remove) -> DKG * 2 -Wait for both/store first-> Vote 2 SectionInfo and signed PublicKey -wait for both/store first-> Split
    => Maybe start Dkg and SectionInfo vote at the same time.
    ==> JP could be problem because with need to sign new Public Key as well
    => Fix things that break.(3 days)
    
   Option B (2DKG): (2-3 days because extra task separated)
    => Add a mechanism for detecting splits in `handle_online_event` (a method in `Chain` that returns whether we should split?) (Already done in previous task).
    => in `handle_online_event`, check whether we should split and vote for either one or two DkgStart events
    => When a DKG completes and we're splitting (need to cache that - is `chain.state.change` enough? (JP not sure, add_member change state.change not clear we should change that?)(JP, should that be related to self.state.new_info?)), vote for the corresponding `SectionInfo`; otherwise, vote for `AddElder`
    => (JP: not call Add in case of split may not be a bad thing in context of node ageing where a lot of additional nodes will be added to elders during split).
    ==> Know what to add remove: `Enum {Split, Vote(Vote)}` if None then split otherwise vote add/remove? 
    ==> (no split) Online -> DKG -> Add/Remove (need to know what to add/remove stored?) -> Vote SectionInfo and signed PublicKey -wait-> Finished 
    ==> ???(split) Online -> detect split: 2 DKG -> 1 DKG complete: Vote for SectionInfo + signed PublicKey -wait for both/store first-> Split
    
    
    Option C (2DKG swap Parsec add and SectionInfo change):
    ==> **Probably a bunch of unknonw problems.**
    ==> (no split) Online -> DKG -> Vote SectionInfo and signed PublicKey -wait-> Add/Remove -> Finished
    ==> ???(split) Online -> detect split: 2 DKG -> 1 DKG complete: Vote for SectionInfo + signed PublicKey -wait for both/store first-> Split

**Comment by jeanphilippeD** [comment]
All items of that Epic that are still relevant are now complete.
DKG is started, and part of the flow. The result is currently ignored, but will be used from Epic 4.
