### ISSUE TITLE
5 - Epic: Switch to real BLS

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/routing#1779]
(Depends on 1, 2, 3, 4)
 (to big to really estimate: need split initial estimate 2-6 Weeks)

 - Replace content of `SectionKeyInfo` with `RealSectionKeyInfo` and remove RealSectionKeyInfo.
 - We will still need to keep signing secret/public key somewhere (maybe new_info/our_infos). (Probably sorted in Epic 4)
 - Other things that will be clearer when 1, 2, 3, 4 are done? 
 - Does it have an impact on tests (Should just work).

Tasks:
 - [x] Use Real BLS: Replace content of `SectionKeyInfo` with `RealSectionKeyInfo` and see what breaks. Fix things. https://github.com/maidsafe/routing/issues/1907
 - [x] Before calling combine, check the 1/3 of signatures are all valid and use only the valid subset + test. #1917 
 - [ ] Follow up clean ups.

**Comment by jeanphilippeD** [comment]
Completed dependent issues. no specific clean up to do.
